name: tempo
description: Aplicativo que mostra a previsão do tempo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  http: ^0.13.5
  geolocator: ^9.0.2
  lottie: ^2.2.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  dartz: ^0.10.1
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/img/

 